round_id: round1
zone_score_weight: 0.2
zone_buffs:
  NO_ZONE:
    buff_min: -0.5
    buff_max: 0.5
    buff_init: 0.0
    target_ratio: 0.2
  SUP_ZONE:
    buff_min: -0.5
    buff_max: 0.5
    buff_init: 0.0
    target_ratio: 0.4
  RES_ZONE:
    buff_min: -0.5
    buff_max: 0.5
    buff_init: 0.0
    target_ratio: 0.4