zone_score_weight: 0.1
no_zone_reward: 1.0
sl_min_dist_bins: 50
sl_max_dist_bins: 100
rr_min: 1
rr_max: 9
action_types: ["BUY", "SELL", "CANCEL_BUY", "CANCEL_SELL", "WAIT_BUY", "WAIT_SELL", "HOLD"]
trend_values: ["UP", "DOWN", "RANGE"]