- symbol: XAUUSD
  timeframe: M1
  scale: 23.95
- symbol: XAUUSD
  timeframe: M5
  scale: 27.38
- symbol: XAUUSD
  timeframe: M15
  scale: 24.74
- symbol: XAUUSD
  timeframe: H1
  scale: 22.81
- symbol: XAUUSD
  timeframe: Daily
  scale: 11.82
- symbol: AUDUSD
  timeframe: M1
  scale: 27.19
- symbol: AUDUSD
  timeframe: M5
  scale: 27.24
- symbol: AUDUSD
  timeframe: M15
  scale: 23.73
- symbol: AUDUSD
  timeframe: H1
  scale: 20.18
- symbol: EURUSD
  timeframe: M1
  scale: 26.83
- symbol: EURUSD
  timeframe: M5
  scale: 28.12
- symbol: EURUSD
  timeframe: M15
  scale: 25.50
- symbol: EURUSD
  timeframe: H1
  scale: 22.96
- symbol: GBPUSD
  timeframe: M1
  scale: 26.89
- symbol: GBPUSD
  timeframe: M5
  scale: 26.50
- symbol: GBPUSD
  timeframe: M15
  scale: 25.32
- symbol: GBPUSD
  timeframe: H1
  scale: 22.15
- symbol: US500
  timeframe: M1
  scale: 30.20
- symbol: US500
  timeframe: M5
  scale: 32.12
- symbol: US500
  timeframe: M15
  scale: 27.86
- symbol: US500
  timeframe: H1
  scale: 26.47